# Generated by Django 2.2.10 on 2020-02-27 18:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('category', models.CharField(max_length=250, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Contact Us Request',
                'verbose_name_plural': 'Contact Us Requests',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Flat Page',
                'verbose_name_plural': 'Flat Pages',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SupportCenterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Support Center',
                'verbose_name_plural': 'Support Center',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SupportCenterElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(verbose_name='Question content')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer text')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', related_query_name='element', to='flatpages.SupportCenterCategory')),
            ],
            options={
                'verbose_name': 'Support Center Element',
                'verbose_name_plural': 'Support Center Elements',
                'ordering': ('category', 'order'),
            },
        ),
    ]
