# Generated by Django 2.2.10 on 2020-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusrequest',
            name='category',
            field=models.CharField(choices=[('questions', 'Questions'), ('suggestions', 'Suggestions')], max_length=250, verbose_name='Category'),
        ),
    ]
